### ISSUE TITLE
Lags

### ISSUE THREAD

**Issue by punkeel** [storm345dev/uCarsRace#1]
Hi,
I know Bukkit.org sucks at notifying you of plugin issues and so on ... But I'd like to re-report it here, to be sure.

From v3 to v4, lags came in and I suspect https://github.com/storm345dev/uCarsRace/commits/master/src/main/java/net/stormdev/urace/lesslag/DynamicLagReducer.java to be responsible for this, at least in some parts.

As you haven't commited a lot, we can't know since what commit lags are happening, so I can't tell you more than "it happens on race end, on lap end" and "lags are on v4 not on v3" ...

Sorry, but thanks too :-)

Have a good day,
- PunKeel

**Comment by storm345** [comment]
Hello, I will investigate the lag, but it is definitely not the mentioned class as that REDUCES lag. :)

Thanks for the notification!

-Sincerely
storm345
